### 예매 생성 API 테스트
POST http://localhost:8080/api/reservations
Content-Type: application/json

{
  "reservations": [
    {
      "screeningId": 101,
      "seats": ["C2", "C3"]
    }
  ],
  "usedPoints": 2000,
  "paymentMethod": "CREDIT_CARD"
}
